//LEFT SIDEBAR TYPE ( 메인 구분 )
export const CHANGE_MODE = 'CHANGE_MODE';

//주제도 ON / OFF
export const THEMATIC_MODE = 'THEMATIC_MODE';

//맵 로딩바
export const LOADING = 'LOADING';


export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const SET_LAYER_LIST = 'SET_LAYER_LIST';
export const REMOVE_LAYER_LIST = 'REMOVE_LAYER_LIST';
export const SET_MAIN_OPTIONS = 'SET_MAIN_OPTIONS';
export const REMOVE_MAIN_OPTIONS = 'REMOVE_MAIN_OPTIONS';

export const ADD_LAYER = 'ADD_LAYER'
export const REMOVE_LAYER = 'REMOVE_LAYER'

//하단 패널
export const LEGNED_PANEL = 'LEGNED_PANEL'

//주소 검색 / 하천검색
export const SEARCH_ADDR = 'SEARCH_ADDR'
export const SEARCH_RIVER = 'SEARCH_RIVER'




////////----------안전-------------
export const SAFETY_TYPE = 'SAFETY_TYPE'
export const SAFETY_TEXT_SAFETY = 'SAFETY_TEXT_SAFETY'
export const SAFETY_START_DATE = 'SAFETY_START_DATE';
export const SAFETY_END_DATE = 'SAFETY_END_DATE';

export const SAFETY_DETAIL_SEARCH_TYPE = 'SAFETY_DETAIL_SEARCH_TYPE';
export const SAFETY_DETAIL_SEARCH_TAB_TYPE = 'SAFETY_DETAIL_SEARCH_TAB_TYPE';
export const SAFETY_DETAIL_RESET = 'SAFETY_DETAIL_RESET';
export const SAFETY_SELECT_RESULT = 'SAFETY_SELECT_RESULT';
export const SAFETY_SELECT_4_LEVEL = 'SAFETY_SELECT_4_LEVEL';
export const SAFETY_SELECT_4_LEVEL_RESET = 'SAFETY_SELECT_4_LEVEL_RESET';
export const SAFETY_SELECT_DISPLACE_LEVEL = 'SAFETY_SELECT_DISPLACE_LEVEL';
export const SAFETY_SELETE_FEATURE = 'SAFETY_SELETE_FEATURE';


////////----------가뭄-------------
export const DROUGHT_SET_TEXT = 'DROUGHT_SET_TEXT'
export const DROUGHT_START_DATE = 'DROUGHT_START_DATE';
export const DROUGHT_END_DATE = 'DROUGHT_END_DATE';
export const DROUGHT_OBSRV_TAB = 'DROUGHT_OBSRV_TAB';
export const DROUGHT_SELETE_FEATURE = 'DROUGHT_SELETE_FEATURE';
export const DROUGHT_SELETE_LAYER = 'DROUGHT_SELETE_LAYER';





////////----------환경-------------
export const ENV_SET_TEXT = 'ENV_SET_TEXT'
export const ENV_START_DATE = 'ENV_START_DATE';
export const ENV_END_DATE = 'ENV_END_DATE';



////////----------홍수-------------
export const FLOOD_SET_TEXT = 'FLOOD_SET_TEXT'
export const FLOOD_START_DATE = 'FLOOD_START_DATE';
export const FLOOD_END_DATE = 'FLOOD_END_DATE';
