export const CHANGE_MODE = 'CHANGE_MODE';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const SET_LAYER_LIST = 'SET_LAYER_LIST';
export const REMOVE_LAYER_LIST = 'REMOVE_LAYER_LIST';
export const SET_MAIN_OPTIONS = 'SET_MAIN_OPTIONS';
export const REMOVE_MAIN_OPTIONS = 'REMOVE_MAIN_OPTIONS';


//하단 패널
export const LEGNED_PANEL = 'LEGNED_PANEL'